version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "3001:3001"
    restart: on-failure:5
    environment:
      - APP_ENV=LOCAL
      - PORT=3001
      - HAS_PROXY=false