// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package api

import (
	"github.com/pazams/go-create-api/pkg/api/config"
	"github.com/pazams/go-create-api/pkg/api/controllers"
	"github.com/pazams/go-create-api/pkg/api/data"
	"github.com/pazams/go-create-api/pkg/api/middlewares"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	dal := data.New(configConfig)
	bookController := controllers.NewBookController(dal)
	pongController := controllers.NewPongController()
	apiAuthMiddleware := middlewares.NewAPIAuthMiddleware(configConfig)
	corsMiddleware := middlewares.NewCORSMiddleware(apiAuthMiddleware)
	handler := NewRouter(bookController, pongController, apiAuthMiddleware, corsMiddleware)
	server, err := NewServer(handler, dal, configConfig)
	if err != nil {
		return nil, err
	}
	return server, nil
}
