// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/pazams/go-create-api/pkg/api/config"
	"github.com/pazams/go-create-api/pkg/api/controllers"
)

// Injectors from wire.go:

// InitializeServer resolves all dependencies for dependency injection and returns the server object
func InitializeServer() (*Server, error) {
	pingController := controllers.NewPingController()
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	handler := NewRouter(pingController, configConfig)
	server, err := NewServer(handler, configConfig)
	if err != nil {
		return nil, err
	}
	return server, nil
}
